// Minimal stub for soc IP to verify top-level compilation
// The real soc.v uses Efinix macro concatenation not supported by iverilog
module soc (
    input io_systemClk,
    input io_asyncReset,
    output io_systemReset,
    // AXI-A Master
    output        axiA_awvalid,
    input         axiA_awready,
    output [31:0] axiA_awaddr,
    output [7:0]  axiA_awid,
    output [3:0]  axiA_awregion,
    output [7:0]  axiA_awlen,
    output [2:0]  axiA_awsize,
    output [1:0]  axiA_awburst,
    output [0:0]  axiA_awlock,
    output [3:0]  axiA_awcache,
    output [3:0]  axiA_awqos,
    output [2:0]  axiA_awprot,
    output        axiA_wvalid,
    input         axiA_wready,
    output [31:0] axiA_wdata,
    output [3:0]  axiA_wstrb,
    output        axiA_wlast,
    input         axiA_bvalid,
    output        axiA_bready,
    input  [7:0]  axiA_bid,
    input  [1:0]  axiA_bresp,
    output        axiA_arvalid,
    input         axiA_arready,
    output [31:0] axiA_araddr,
    output [7:0]  axiA_arid,
    output [3:0]  axiA_arregion,
    output [7:0]  axiA_arlen,
    output [2:0]  axiA_arsize,
    output [1:0]  axiA_arburst,
    output [0:0]  axiA_arlock,
    output [3:0]  axiA_arcache,
    output [3:0]  axiA_arqos,
    output [2:0]  axiA_arprot,
    input         axiA_rvalid,
    output        axiA_rready,
    input  [31:0] axiA_rdata,
    input  [7:0]  axiA_rid,
    input  [1:0]  axiA_rresp,
    input         axiA_rlast,
    input         axiAInterrupt,
    input         userInterruptA,
    // JTAG
    input  jtagCtrl_tck,
    input  jtagCtrl_tdi,
    input  jtagCtrl_enable,
    input  jtagCtrl_capture,
    input  jtagCtrl_shift,
    input  jtagCtrl_update,
    input  jtagCtrl_reset,
    output jtagCtrl_tdo,
    // UART
    output system_uart_0_io_txd,
    input  system_uart_0_io_rxd,
    // I2C
    input  system_i2c_0_io_scl_read,
    output system_i2c_0_io_scl_write,
    input  system_i2c_0_io_sda_read,
    output system_i2c_0_io_sda_write,
    // GPIO
    input  [3:0] system_gpio_0_io_read,
    output [3:0] system_gpio_0_io_write,
    output [3:0] system_gpio_0_io_writeEnable,
    // SPI
    output system_spi_0_io_sclk_write,
    output system_spi_0_io_data_0_writeEnable,
    input  [0:0] system_spi_0_io_data_0_read,
    output [0:0] system_spi_0_io_data_0_write,
    output system_spi_0_io_data_1_writeEnable,
    input  [0:0] system_spi_0_io_data_1_read,
    output [0:0] system_spi_0_io_data_1_write,
    output system_spi_0_io_data_2_writeEnable,
    input  [0:0] system_spi_0_io_data_2_read,
    output [0:0] system_spi_0_io_data_2_write,
    output system_spi_0_io_data_3_writeEnable,
    input  [0:0] system_spi_0_io_data_3_read,
    output [0:0] system_spi_0_io_data_3_write,
    output [0:0] system_spi_0_io_ss,
    // APB
    output [15:0] io_apbSlave_0_PADDR,
    output        io_apbSlave_0_PENABLE,
    input  [31:0] io_apbSlave_0_PRDATA,
    input         io_apbSlave_0_PREADY,
    output [0:0]  io_apbSlave_0_PSEL,
    input         io_apbSlave_0_PSLVERROR,
    output [31:0] io_apbSlave_0_PWDATA,
    output        io_apbSlave_0_PWRITE
);
endmodule
